name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          cat <<EOF > .env
          NEXT_PUBLIC_SITE_URL="https://tinyscript.io"
          SUPABASE_AUTH_EXTERNAL_GITHUB_REDIRECT_URI="https://tinyscript.io/auth/callback"
          SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID="Ov23liHguQqCX8GveevF"
          SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET="f86da30b2a27e7d99fdb05cce001d3e1eb687769"
          SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI="https://tinyscript.io/auth/callback"
          SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID="772670371516-3e9qpq3d0r9pm9tsndr6035qr2flak7q.apps.googleusercontent.com"
          SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET="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"
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="pk_test_51PqzyfGq5NXltWykwAxT7e6pq1YaEdKf7uyjNnI5r259tm34iv1imtThLDpEzTmNogrSPJQ3cZRm8X3o1OaCVazt004sof6eBi"
          STRIPE_SECRET_KEY="sk_test_51PqzyfGq5NXltWykaX6tetM78TWNSYYUPPnh1d5eOzymrelgCRRoie5ifOA1e0B3CrMsjLLoCxbeJDUlJWQQ2MbA005Tad5Y7Y"
          STRIPE_WEBHOOK_SECRET="whsec_e7d831cf9f1d9900cced8dfdf0ed62605f6b4071b9d95632202f4e827142aba6"
          NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5YXNnZ254c3J6eXZtanhnb2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjUxOTU5NTksImV4cCI6MjA0MDc3MTk1OX0.g9BGa2UD07IOkqCPMsYreAZ6xNxVCIDQ-B4QBC_ijcM"
          NEXT_PUBLIC_SUPABASE_URL="https://ayasggnxsrzyvmjxgolp.supabase.co"
          SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5YXNnZ254c3J6eXZtanhnb2xwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyNTE5NTk1OSwiZXhwIjoyMDQwNzcxOTU5fQ.snplz67vKs279y0f5Qn3yqS2glI1pq8HrxdH-3tTIIQ"
          REPLICATE_API_TOKEN="r8_OXegDY4kkkbaJXrRXDvmxfkrAXSYUTJ21rSTA"
          SYSTEM_PROMPT="You are a helpful assistant that can answer questions and help with tasks. You are a helpful assistant that can answer questions and help with tasks."
          EOF
        shell: bash

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . --platform linux/amd64 -t ghcr.io/jimmyflatting/tinyscript:latest
          docker push ghcr.io/jimmyflatting/tinyscript

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull ghcr.io/jimmyflatting/tinyscript:latest
            docker stop tinyscript
            docker rm tinyscript
            docker run -d -p 3000:3000 --name tinyscript ghcr.io/jimmyflatting/tinyscript:latest
