name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          cat <<EOF > .env
          DATABASE="mongodb+srv://jimmyflatting:LtCXZXsBYz1YXkEW@tinyscript.zm0j4.mongodb.net/?retryWrites=true&w=majority&appName=tinyscript"
          REPLICATE_API_TOKEN="r8_OXegDY4kkkbaJXrRXDvmxfkrAXSYUTJ21rSTA"
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="pk_test_51PqzyfGq5NXltWykwAxT7e6pq1YaEdKf7uyjNnI5r259tm34iv1imtThLDpEzTmNogrSPJQ3cZRm8X3o1OaCVazt004sof6eBi"
          STRIPE_SECRET_KEY="sk_test_51PqzyfGq5NXltWykaX6tetM78TWNSYYUPPnh1d5eOzymrelgCRRoie5ifOA1e0B3CrMsjLLoCxbeJDUlJWQQ2MbA005Tad5Y7Y"
          SYSTEM_PROMPT="You are a helpful assistant that can answer questions and help with tasks. You are a helpful assistant that can answer questions and help with tasks."
          NEXT_PUBLIC_GOOGLE_CLIENT_ID="772670371516-3e9qpq3d0r9pm9tsndr6035qr2flak7q.apps.googleusercontent.com"
          EOF
        shell: bash

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . --platform linux/amd64 -t ghcr.io/jimmyflatting/tinyscript:latest
          docker push ghcr.io/jimmyflatting/tinyscript

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull ghcr.io/jimmyflatting/tinyscript:latest
            docker stop tinyscript
            docker rm tinyscript
            docker run -d -p 3000:3000 --name tinyscript ghcr.io/jimmyflatting/tinyscript:latest
